#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2154,SC2034  # las claves llevan puntos y shellcheck lee MSG[a.b]
# como aritmetica; el array MSG lo declara y lo lee scripts/lib/i18n.sh, que hace source
# de este archivo.
# English message catalog. Loaded by scripts/lib/i18n.sh; not executable.
#
# Keys are dot separated, lowercase, and prefixed with the script they belong to.
# scripts/lib/i18n/es.sh MUST define exactly the same set of keys: scripts/i18n-check.sh
# fails otherwise. Placeholders are printf placeholders (%s, %d); a literal per cent sign is
# written %%.

# --- ui.sh ------------------------------------------------------------------------------------
MSG[ui.label.ok]="OK     "
MSG[ui.label.warn]="WARN   "
MSG[ui.label.miss]="MISSING"
MSG[ui.error]="Error:"
MSG[ui.confirm.yes]="[Y/n]"
MSG[ui.confirm.no]="[y/N]"

# --- lib/oci-instance.sh ------------------------------------------------------------------------
MSG[oci.ocid.fail]="oci-instance: ERROR: could not resolve the instance OCID.
  Try: cd infra/terraform/envs/prod && tofu output -raw instance_ocid
  Or export INSTANCE_OCID=ocid1.instance.oc1...."
MSG[oci.cli.missing]="oci-instance: ERROR: the 'oci' CLI is missing. Install it in a venv (see docs/runbook.md)."

# --- lib/notificar.sh ---------------------------------------------------------------------------
MSG[notif.json.fail]="WARNING: could not build the webhook JSON (are jq and python3 both missing?)"
MSG[notif.post.fail]="WARNING: the POST to the Discord webhook failed"

# --- setup.sh -----------------------------------------------------------------------------------
MSG[setup.help]="Project Zomboid server configuration assistant.

  ./setup.sh                 # normal mode: asks each question and explains it
  ./setup.sh --no-preguntar  # asks nothing: uses the ZS_* environment variables
  ./setup.sh --ayuda

It checks the required tools, helps you connect your Oracle Cloud account, generates the
passwords for you and writes the two configuration files the deployment needs:

  infra/terraform/envs/prod/terraform.tfvars   (read by OpenTofu to create the machine)
  .env                                          (server configuration; the cloud one is
                                                 generated by cloud-init from the tfvars)

It can be re-run as often as needed: previous answers come back as defaults and only what you
change is changed.

--no-preguntar mode (used by the tests and by CI). Accepted variables:
  ZS_LANG
  ZS_PUBLIC_NAME  ZS_MAX_PLAYERS  ZS_OCPUS  ZS_MEMORY_GB  ZS_ALERT_EMAIL  ZS_BUDGET_USD
  ZS_REGION
  ZS_TENANCY_OCID  ZS_ADMIN_CIDR  ZS_SSH_PUBLIC_KEY  ZS_REPO_URL  ZS_BUCKET_NAME
  ZS_ADMIN_PASSWORD  ZS_RCON_PASSWORD  ZS_SERVER_PASSWORD
  ZS_SKIP_OCI=1     skips the ~/.oci/config and oci CLI checks"
MSG[setup.unknown_option]="unknown option: %s (try ./setup.sh --ayuda)"
MSG[setup.pause.default]="Press Enter when you are done."
MSG[setup.pause.start]="Press Enter to start."
MSG[setup.welcome]="
  ============================================================
   Project Zomboid server: configuration assistant
  ============================================================

  This does NOT create anything in the cloud yet and does NOT cost money. It only prepares the
  configuration files. Later, when you want to, you run  make deploy  and the server is created.

  You will need:
    - an Oracle Cloud account, already created and with a card on file (the README explains how)
    - an email address for the spending alerts
    - about 5 minutes

  If something is unclear, press Enter to accept the value in brackets: they are sensible
  starting values."
MSG[setup.tools.title]="1. Tools on this computer"
MSG[setup.tools.install_hint]="Install it with:  sudo apt install %s   (or your system package manager)"
MSG[setup.bash.old]="bash %s: bash 4 or newer is required"
MSG[setup.bash.macos]="On macOS:  brew install bash  then run ./setup.sh again with the new bash"
MSG[setup.tools.missing]="install what is missing and run ./setup.sh again"
MSG[setup.tofu.unzip]="'unzip' is required:  sudo apt install unzip"
MSG[setup.tofu.downloading]="  Downloading OpenTofu %s..."
MSG[setup.tofu.ok]="OpenTofu %s"
MSG[setup.tofu.missing]="OpenTofu: the program that creates the machine in the cloud"
MSG[setup.tofu.confirm]="Install it in ~/.local/bin (no sudo needed)?"
MSG[setup.tofu.installed]="OpenTofu installed in ~/.local/bin/tofu"
MSG[setup.tofu.install_failed]="could not install OpenTofu. Manual instructions: docs/runbook.md 1.5"
MSG[setup.tofu.manual]="Manual instructions: docs/runbook.md 1.5"
MSG[setup.tofu.required]="OpenTofu is required to deploy"
MSG[setup.ssh.from_env]="SSH key taken from ZS_SSH_PUBLIC_KEY"
MSG[setup.ssh.found]="SSH key: %s"
MSG[setup.ssh.missing]="you have no SSH key (it is what lets you into the cloud machine)"
MSG[setup.ssh.confirm]="Create it now? (it will not ask for a passphrase)"
MSG[setup.ssh.created]="key created in %s"
MSG[setup.ssh.required]="an SSH key is required. Create it with:  ssh-keygen -t ed25519"
MSG[setup.ssh.bad_format]="the SSH public key does not have the expected shape (it has to start with ssh-ed25519)"
MSG[setup.gh.ok]="GitHub CLI connected (only used if your repository is private)"
MSG[setup.gh.missing]="GitHub CLI (gh) is missing or not connected: that is fine, it is optional"
MSG[setup.oci.title]="2. Oracle Cloud account"
MSG[setup.oci.python]="python3 is required"
MSG[setup.oci.skipped]="ZS_SKIP_OCI=1: skipping the Oracle Cloud account check"
MSG[setup.oci.apikey]="
  Your Oracle Cloud account is not connected to this computer yet. It is a file with a key
  that Oracle generates for you. Do it like this (5 minutes):

   1. Go to https://cloud.oracle.com and sign in.
   2. Top right, the person icon -> \"My profile\".
   3. In the left menu, \"API keys\" -> \"Add API key\".
   4. Leave \"Generate API key pair\" selected and press \"Download private key\".
      A .pem file is downloaded: keep it, it is your key.
   5. Press \"Add\". Oracle shows a text box with several lines
      (user=..., fingerprint=..., tenancy=..., region=...). Copy the whole thing.
   6. On this computer, in another terminal, run:

        mkdir -p ~/.oci && chmod 700 ~/.oci
        mv ~/Downloads/*.pem ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        nano ~/.oci/config

      Paste the box you copied and add this line at the end:

        key_file=/home/YOUR_USER/.oci/oci_api_key.pem

      Save with Ctrl+O, Enter, Ctrl+X. Then:

        chmod 600 ~/.oci/config"
MSG[setup.oci.pause]="Press Enter once it is ready."
MSG[setup.oci.config_ok]="account file: %s"
MSG[setup.oci.key_ok]="API private key: %s"
MSG[setup.oci.key_bad]="the key_file= line in %s points to a file that does not exist"
MSG[setup.oci.key_hint]="Fix it with the full path of the .pem you downloaded from Oracle."
MSG[setup.oci.config_missing]="%s is still missing: you can continue, but 'make deploy' will fail"
MSG[setup.oci.cli_ok]="oci CLI installed"
MSG[setup.oci.cli_missing]="the 'oci' program is missing (it starts and stops the server, and runs checks)"
MSG[setup.oci.cli_confirm]="Install it in ~/.venvs/oci (no sudo)?"
MSG[setup.oci.cli_installed]="oci installed (~/.local/bin/oci)"
MSG[setup.oci.cli_failed]="could not install the oci CLI; continuing without it"
MSG[setup.oci.auth_ok]="the Oracle Cloud account answers: the key is configured correctly"
MSG[setup.oci.auth_fail]="Oracle does not accept the key yet"
MSG[setup.oci.auth_hint1]="Check user=, fingerprint=, tenancy= and key_file= in %s."
MSG[setup.oci.auth_hint2]="To see the full error:  oci iam region list"
MSG[setup.server.title]="3. How you want your server"
MSG[setup.q.lang]="Idioma / Language"
MSG[setup.q.public_name]="Server name (the one your friends see)"
MSG[setup.default.public_name]="My Zomboid Server"
MSG[setup.err.public_name]="the name cannot contain double quotes, backslashes, dollar signs or backticks"
MSG[setup.q.max_players]="Maximum number of players"
MSG[setup.err.max_players]="the player count has to be a number"
MSG[setup.err.ocpus]="ZS_OCPUS has to be a whole number of 1 or more"
MSG[setup.err.memory]="ZS_MEMORY_GB has to be a whole number of 6 or more (the JVM heap is memory_gb - 4)"
MSG[setup.q.alert_email]="Email address for the Oracle spending alerts"
MSG[setup.err.alert_email]="a valid email address is required for the spending alerts"
MSG[setup.q.budget]="Warn about spending when the month goes over (USD)"
MSG[setup.err.budget]="the budget has to be a whole number"
MSG[setup.region.saopaulo]="Sao Paulo, Brazil        | ~30 ms from Argentina  (recommended here)"
MSG[setup.region.vinhedo]="Vinhedo, Brazil          | ~30 ms from Argentina"
MSG[setup.region.santiago]="Santiago, Chile          | ~25-35 ms from Argentina"
MSG[setup.region.ashburn]="Ashburn, US East         | ~140 ms from Argentina, ~20 ms from the US east coast"
MSG[setup.region.phoenix]="Phoenix, US West         | ~180 ms from Argentina, ~20 ms from the US west coast"
MSG[setup.region.frankfurt]="Frankfurt, Germany       | ~230 ms from Argentina, ~20 ms from Europe"
MSG[setup.region.madrid]="Madrid, Spain            | ~210 ms from Argentina, ~20 ms from Spain"
MSG[setup.region.london]="London, United Kingdom   | ~220 ms from Argentina, ~15 ms from the UK"
MSG[setup.region.intro]="
  Region (where the machine will be). Pick the one closest to where the players live:"
MSG[setup.region.warning]="
  IMPORTANT: it has to be the SAME region you chose when you created the Oracle account
  (the \"home region\"). If it does not match, the deployment fails. If you do not remember it,
  it is the one shown at the top right of the Oracle console."
MSG[setup.q.region]="Region number, or type the code yourself"
MSG[setup.err.region]="the region code does not look valid: %s"
MSG[setup.region.mismatch]="you chose %s but your account says %s"
MSG[setup.region.mismatch_hint]="If the deployment fails with 'NotAuthorizedOrNotFound', use your account's one."
MSG[setup.q.tenancy]="Your Oracle account ID (the 'tenancy=' line in ~/.oci/config)"
MSG[setup.err.tenancy]="the account ID has to start with ocid1.tenancy. Take it from %s"
MSG[setup.err.no_ip]="could not find out your public IP. Set it by hand: curl https://ifconfig.me"
MSG[setup.admin_cidr.intro]="
  Your internet IP is the only one you will be able to administer the server from.
  (Your friends still join from anywhere: this is only for administration.)
  If your connection changes IP, run ./setup.sh and make deploy again later."
MSG[setup.q.admin_cidr]="Your admin IP"
MSG[setup.err.admin_cidr]="the admin IP has to look like 1.2.3.4/32"
MSG[setup.repo.title]="4. Where the machine gets the configuration from"
MSG[setup.repo.public]="your repository is public: the machine clones it on its own, nothing else to do"
MSG[setup.repo.private]="your repository is private (or does not exist yet)"
MSG[setup.repo.private_hint1]="%s will be used, with a read-only key registered on GitHub."
MSG[setup.repo.private_hint2]="To avoid that step, make the repository public in GitHub -> Settings -> General."
MSG[setup.repo.ssh]="your repository is cloned over SSH: a read-only key will be used"
MSG[setup.repo.key_no]="no"
MSG[setup.repo.key_yes]="yes"
MSG[setup.repo.summary]="  Repository: %s   (read-only key: %s)"
MSG[setup.pass.title]="5. Passwords"
MSG[setup.pass.intro]="  Three different passwords are generated. You do not have to memorise them: they are stored
  in the configuration files, and 'make deploy' shows you the one to give to your friends.

    - server:  the one your friends type to join
    - admin:   your administrator account inside the game
    - RCON:    used by the tooling to talk to the server, nobody types it"
MSG[setup.pass.label.server]="server"
MSG[setup.pass.label.admin]="admin"
MSG[setup.pass.label.rcon]="RCON"
MSG[setup.q.password]="%s password (Enter accepts the suggested one)"
MSG[setup.err.password]="the %s password has to be 8 to 64 characters, with no spaces, quotes, backslashes or dollar signs"
MSG[setup.write.title]="6. Saving the configuration"
MSG[setup.mods.count]="config/mods.txt (%s Workshop mods)"
MSG[setup.mods.vanilla]="config/mods.txt (no active mods: vanilla game)"
MSG[setup.mods.created]="config/mods.txt created (vanilla game, no mods)"
MSG[setup.mods.hint1]="To add mods edit config/mods.txt: one line per Workshop item, the format is"
MSG[setup.mods.hint2]="explained inside the file and in docs/mods.md. Applied by make deploy or make restart."
MSG[setup.sandbox.created]="config/servertest_SandboxVars.lua created (vanilla game rules)"
MSG[setup.sandbox.hint1]="To change the rules edit that file (each value is explained inside) or use the"
MSG[setup.sandbox.hint2]="survey (docs/survey.md). Several rules are fixed when the world is created: decide them before the first game."
MSG[setup.summary.mods_some]="%s (config/mods.txt)"
MSG[setup.summary.mods_none]="none, vanilla game (config/mods.txt)"
MSG[setup.summary]="
  ============================================================
   Done. This is how it is configured:
  ============================================================

    Server name ............ %s
    Maximum players ........ %s
    Machine ................ %s OCPU / %s GB (JVM heap: %s)
    Region ................. %s
    Spending alerts ........ %s (from %s USD/month)
    Administration from .... %s
    Server password ........ %s
    Mods ................... %s

  Now:

    make doctor     checks that everything is ready (optional, 10 seconds)
    make deploy     creates the server in the cloud (20-40 minutes the first time)

  From here on it DOES cost money: around 90 USD/month with the machine running all the time.
  To stop paying:  make destroy-all"

# --- scripts/doctor.sh ----------------------------------------------------------------------------
MSG[doctor.help]="Checks that everything is ready to deploy and operate the server, and explains in one line
what to do about anything that is missing.

  make doctor            # full check
  scripts/doctor.sh -q   # only what is wrong (used by scripts/deploy.sh before starting)

Exit codes:
  0  everything blocking is in order (there may be warnings)
  1  something is missing without which \`make deploy\` cannot work"
MSG[doctor.unknown_option]="unknown option: %s"
MSG[doctor.header]="
  ============================================================
   Project Zomboid server check
  ============================================================"
MSG[doctor.title.1]="1. Required programs"
MSG[doctor.bash.old]="bash %s is too old (4 or newer is required)"
MSG[doctor.bash.macos]="On macOS:  brew install bash"
MSG[doctor.cmd.missing]="%s is missing"
MSG[doctor.cmd.hint]="Install it with:  sudo apt install %s"
MSG[doctor.tofu.ok]="OpenTofu %s"
MSG[doctor.tofu.missing]="OpenTofu is missing (it is the program that creates the machine in the cloud)"
MSG[doctor.tofu.hint]="Run ./setup.sh: it installs it for you in ~/.local/bin"
MSG[doctor.ssh.ok]="SSH key: %s"
MSG[doctor.ssh.missing]="you have no SSH key (it is what lets you into the machine)"
MSG[doctor.ssh.hint]="Create it with:  ssh-keygen -t ed25519"
MSG[doctor.gh.ok]="GitHub CLI connected (optional: used to register the key for a private repository)"
MSG[doctor.gh.missing]="GitHub CLI (gh) is missing or not connected: it is optional"
MSG[doctor.gh.hint]="Only needed if your repository is private. It can also be done by hand on the web."
MSG[doctor.title.2]="2. Oracle Cloud account"
MSG[doctor.oci.profile_ok]="%s with a [DEFAULT] profile"
MSG[doctor.oci.profile_missing]="%s has no [DEFAULT] profile"
MSG[doctor.oci.profile_hint]="The first line of the file has to be exactly:  [DEFAULT]"
MSG[doctor.oci.key_ok]="API private key: %s"
MSG[doctor.oci.key_missing]="the key_file= line in %s does not point to an existing file"
MSG[doctor.oci.key_hint]="Use the full path of the .pem you downloaded from Oracle, for example %s"
MSG[doctor.oci.config_missing]="%s does not exist: this computer is not connected to your Oracle account"
MSG[doctor.oci.config_hint]="Run ./setup.sh: it walks you through creating the API key."
MSG[doctor.oci.cli_ok]="the 'oci' program is installed"
MSG[doctor.oci.auth_ok]="Oracle accepts your key: the account answers"
MSG[doctor.oci.auth_fail]="Oracle does not accept your key yet"
MSG[doctor.oci.auth_hint1]="To see the full error:  oci iam region-subscription list"
MSG[doctor.oci.auth_hint2]="Check user=, fingerprint=, tenancy= and key_file= in %s."
MSG[doctor.oci.cli_missing]="the 'oci' program is not installed"
MSG[doctor.oci.cli_hint1]="Not strictly needed to deploy, but it starts and stops the server."
MSG[doctor.oci.cli_hint2]="Run ./setup.sh and accept the install (it goes to ~/.venvs/oci, no sudo)."
MSG[doctor.title.3]="3. Your server configuration"
MSG[doctor.tfvars.placeholder]="terraform.tfvars still has example values (it says CAMBIAME)"
MSG[doctor.tfvars.placeholder_hint]="Run ./setup.sh to fill it in."
MSG[doctor.tfvars.key_missing]="%s is missing from terraform.tfvars"
MSG[doctor.setup_hint]="Run ./setup.sh."
MSG[doctor.tfvars.perms]="terraform.tfvars has permissions %s: it contains passwords"
MSG[doctor.tfvars.perms_hint]="Fix it with:  chmod 600 %s"
MSG[doctor.tfvars.missing]="terraform.tfvars does not exist: the server is not configured"
MSG[doctor.env.missing]=".env does not exist"
MSG[doctor.env.hint]="Only needed to run the server on this computer. ./setup.sh creates it."
MSG[doctor.mods.count]="config/mods.txt: %s Workshop mods"
MSG[doctor.mods.vanilla]="config/mods.txt: no active mods (vanilla game)"
MSG[doctor.mods.vanilla_hint]="To add mods, edit config/mods.txt (the format is inside it and in docs/mods.md)."
MSG[doctor.mods.missing]="config/mods.txt does not exist: the game will be vanilla (no mods)"
MSG[doctor.mods.missing_hint]="./setup.sh creates it, or:  cp config/mods.example.txt config/mods.txt"
MSG[doctor.sandbox.missing]="config/servertest_SandboxVars.lua does not exist: vanilla game rules"
MSG[doctor.sandbox.hint]="./setup.sh creates it, or:  cp config/servertest_SandboxVars.example.lua config/servertest_SandboxVars.lua"
MSG[doctor.repo.public]="the repository %s is public: the machine will be able to clone it"
MSG[doctor.repo.private]="the repository %s cannot be cloned without a password"
MSG[doctor.repo.private_hint1]="Make it public in GitHub -> Settings -> General -> Change visibility,"
MSG[doctor.repo.private_hint2]="or run ./setup.sh again to use a read-only key."
MSG[doctor.repo.ssh]="the repository %s is cloned over SSH with a read-only key"
MSG[doctor.repo.key_ok]="the repository already has a read-only key registered on GitHub"
MSG[doctor.repo.key_missing]="the repository has no key registered on GitHub yet"
MSG[doctor.repo.key_hint]="'make deploy' will register it for you."
MSG[doctor.repo.unreadable]="could not read repo_url from terraform.tfvars"
MSG[doctor.title.4]="4. Server in the cloud"
MSG[doctor.cloud.none]="nothing deployed yet (nothing created, nothing being charged)"
MSG[doctor.cloud.none_hint]="When you want to create it:  make deploy"
MSG[doctor.cloud.ip]="server IP: %s"
MSG[doctor.cloud.ip_unknown]="unknown"
MSG[doctor.cloud.running]="the machine is RUNNING (and being charged)"
MSG[doctor.cloud.running_hint]="To see whether the game answers:  make remote-status"
MSG[doctor.cloud.stopped]="the machine is STOPPED (no compute charge, only the disk)"
MSG[doctor.cloud.stopped_hint]="To start it:  ./scripts/cloud-start.sh"
MSG[doctor.cloud.state_unknown]="could not query the state of the machine"
MSG[doctor.cloud.state_hint]="Try:  oci compute instance get --instance-id %s"
MSG[doctor.cloud.state_other]="machine state: %s"
MSG[doctor.backup.last]="last backup saved: %s"
MSG[doctor.backup.none]="there are no backups in the cloud yet (bucket %s)"
MSG[doctor.backup.none_hint]="The automatic backup runs every day. To force one:  make remote-backup"
MSG[doctor.cloud.no_oci]="cannot query the state of the machine without the 'oci' program configured"
MSG[doctor.final.ok]="
  ------------------------------------------------------------
   Everything is ready. The next step is:   make deploy
  ------------------------------------------------------------"
MSG[doctor.final.problems]="
  ------------------------------------------------------------
   There are %s item(s) marked as MISSING above.
   Fix them (running ./setup.sh is almost always enough) and try again with: make doctor
  ------------------------------------------------------------"

# --- scripts/deploy.sh ------------------------------------------------------------------------------
MSG[deploy.help]="Creates (or updates) the server in the cloud, end to end.

  make deploy              # the normal path: shows what it will do and confirms once
  make deploy YES=1        # no confirmation
  scripts/deploy.sh --dry-run   # only prints the steps, touches nothing and costs nothing

The steps are:
  1. pre-flight check (scripts/doctor.sh)
  2. tofu init                       (downloads the Oracle Cloud plugins)
  3. if the repository is private: create the read-only key and register it on GitHub
  4. tofu apply                      (this is where the machine is created: charging starts)
  5. wait for the machine to accept connections            (up to 10 minutes)
  6. wait for the game to install and start                (up to 30 minutes)
  7. print what to give to your friends

It is idempotent: if everything is deployed already, nothing changes and the details are
printed again."
MSG[deploy.unknown_option]="unknown option: %s"
MSG[deploy.simulated]="          (simulated) %s"
MSG[deploy.step1]="Step 1 of 7: checking that everything is in order"
MSG[deploy.ok]="everything is in order"
MSG[deploy.dryrun_warn]="something is missing, but since this is a simulation I continue to show you the steps"
MSG[deploy.blocked]="
  I cannot continue until the problem above is resolved.
  In most cases running this is enough:  ./setup.sh"
MSG[deploy.no_tfvars]="%s is missing. Run ./setup.sh"
MSG[deploy.step2]="Step 2 of 7: preparing the tools (downloaded only once)"
MSG[deploy.step3.public]="Step 3 of 7: your repository is public, the machine clones it on its own (nothing to do)"
MSG[deploy.step3.private]="Step 3 of 7: read-only key so the machine can clone your private repository"
MSG[deploy.key.loaded]="the key was already registered on GitHub"
MSG[deploy.key.simulated]="gh repo deploy-key add ... -R %s --title zomboid-vm"
MSG[deploy.key.added]="key registered on GitHub automatically"
MSG[deploy.key.manual]="
  The machine needs permission to clone your private repository. It is a copy and paste:

   1. Copy this whole line (it is a key that can only READ your repository):

%s

   2. Go to your repository on GitHub -> Settings -> Deploy keys -> \"Add deploy key\".
   3. Title: zomboid-vm       Key: paste the line above.
   4. Do NOT tick \"Allow write access\".
   5. Press \"Add key\"."
MSG[deploy.key.prompt]="  Press Enter once you have registered it: "
MSG[deploy.step4]="Step 4 of 7: creating the server in Oracle Cloud"
MSG[deploy.money]="
  Above is the list of what will be created in Oracle Cloud.
  From here on CHARGING STARTS: around 90 USD per month with the machine running all the time.
  To stop paying at any time:  make destroy-all"
MSG[deploy.confirm]="Create the server?"
MSG[deploy.cancelled]="  Cancelled. Nothing was created."
MSG[deploy.ip_fail]="the server was created but I could not read its IP. Try: %s -chdir=%s output"
MSG[deploy.ip]="server IP: %s"
MSG[deploy.step5]="Step 5 of 7: waiting for the machine to come up (up to 10 minutes)"
MSG[deploy.ssh.simulated]="ssh %s@%s true  in a loop until it answers"
MSG[deploy.ssh_ok]="the machine answers"
MSG[deploy.waiting]="waiting"
MSG[deploy.ssh_timeout]="
  The machine did not answer within 10 minutes. Things to check:
    - Did your internet IP change? Run ./setup.sh again and then make deploy.
    - In the Oracle console, is the instance listed as RUNNING?
    - More help: docs/runbook.md, section \"No entra por SSH\"."
MSG[deploy.step6]="Step 6 of 7: installing and starting the game (up to 30 minutes the first time)"
MSG[deploy.patience]="          This takes a while because the machine downloads the whole game (about 10 GB)
          and installs it. You can leave it running and go do something else. Stopping it
          with Ctrl+C breaks nothing: the server keeps installing and you can come back
          with make deploy."
MSG[deploy.logs.simulated]="ssh %s@%s 'cd /opt/zomboid-server && docker compose logs zomboid'"
MSG[deploy.logs.simulated2]="until '*** SERVER STARTED ****' shows up, or 30 minutes elapse"
MSG[deploy.phase.preparing]="preparing the machine and downloading the game"
MSG[deploy.phase.starting]="starting the game"
MSG[deploy.phase.default]="preparing the machine"
MSG[deploy.cloudinit_error]="
  Preparing the machine failed. To see why:

    ssh USER@IP 'sudo tail -50 /var/log/cloud-init-output.log'

  The most common case is the repository read-only key not being registered on GitHub.
  More help: docs/runbook.md, \"El server no arranca despues de un tofu apply\"."
MSG[deploy.slow]="
  30 minutes went by and the game has not finished starting. It is not necessarily broken:
  on a slow connection the first start can take longer. To watch what it is doing live:

    make remote-logs

  Run  make deploy  again whenever you want and it picks up from here."
MSG[deploy.game_up]="the game is up"
MSG[deploy.step7]="Step 7 of 7: done"
MSG[deploy.final]="
  ============================================================
   GIVE THIS TO YOUR FRIENDS
  ============================================================

   In Project Zomboid: Join -> Favorites tab -> Add server

     Name .................... %s
     IP ...................... %s
     Port .................... %s
     Server password ......... %s

     The \"Account username\" and \"Account password\" are each player's own: they are created
     automatically the first time they join.

  ============================================================
   YOUR 5 COMMANDS
  ============================================================

     make remote-status      is it up? who is playing?
     make remote-logs        see what is happening (Ctrl+C to exit)
     make remote-restart     restart (applies mod or rule changes)
     make remote-backup      save a copy of the game right now
     make destroy-all        delete everything and stop paying

   To add mods: edit config/mods.txt (format inside the file) and run  make sync RESTART=1
   Full manual: README.md      Advanced reference: docs/runbook.md"

# --- scripts/destroy-all.sh -------------------------------------------------------------------------
MSG[destroy.help]="Deletes the cloud server to stop paying for it.

  make destroy-all          # asks you to type the server name to confirm
  scripts/destroy-all.sh --dry-run

Before deleting it tries to save one last copy of the game in the cloud, so you can bring
everything back later with \`make deploy\` + \`scripts/restore.sh\`."
MSG[destroy.unknown_option]="unknown option: %s"
MSG[destroy.default_name]="My Zomboid Server"
MSG[destroy.simulated]="          (simulated) %s"
MSG[destroy.nothing]="
  I cannot find any server created from this computer (there is no OpenTofu state).

  If you already deleted it, there is nothing to do and you are not being charged for the
  machine. If you created it from ANOTHER computer, delete it from there, or by hand in the
  Oracle Cloud console: menu -> Compute -> Instances -> the three dots -> Terminate."
MSG[destroy.confirm_block]="
  ============================================================
   DELETE EVERYTHING
  ============================================================

  This is deleted, with no way back:

    - the server machine (%s)
    - its disk, with whatever game is on it
    - the network and the reserved IP (your friends will need the new IP if you create it again)

  This is NOT deleted:

    - the backups stored in the cloud (bucket \"%s\")
      They keep being charged, but it is cents: about 0.03 USD per GB per month.

  Before deleting I will try to save one last copy of the game."
MSG[destroy.no_ip]="no IP"
MSG[destroy.confirm_prompt]="  Type the server name (%s) to confirm: "
MSG[destroy.mismatch]="does not match: nothing was deleted"
MSG[destroy.step.backup]="Saving one last copy of the game"
MSG[destroy.backup.simulated]="ssh %s@%s 'cd /opt/zomboid-server && ./scripts/backup.sh final'"
MSG[destroy.backup_ok]="copy saved in the cloud with the label 'final'"
MSG[destroy.backup_fail]="the final copy failed"
MSG[destroy.confirm_anyway]="Delete anyway?"
MSG[destroy.cancelled]="cancelled: nothing was deleted"
MSG[destroy.vm_down]="the machine does not answer (it may be stopped): the final copy could not be made"
MSG[destroy.step.destroy]="Deleting the server (takes 2-5 minutes)"
MSG[destroy.final]="
  ============================================================
   Done: the server no longer exists and you stopped paying for it
  ============================================================

  The only thing that can still cost a minimal amount is the backups stored in Oracle Cloud,
  in the bucket \"%s\". They are a few cents a month and they are what you need if you ever
  want to bring the game back:

     make deploy
     ssh USER@NEW_IP 'cd /opt/zomboid-server && ./scripts/restore.sh oci:%s/FILE.tar.zst'

  If you want to delete the copies too and leave nothing behind:

     In the console: menu -> Storage -> Buckets -> %s -> delete the objects and then the
     bucket. Then, menu -> Identity -> Compartments -> zomboid -> Delete (only possible once
     it is empty).

  With the 'oci' program installed, the same from the terminal:

     oci os object bulk-delete --bucket-name %s --namespace %s
     oci os bucket delete --bucket-name %s --namespace %s

  Check that nothing is still being billed in: Billing & Cost Management -> Cost Analysis
  (region %s)."

# --- scripts/render-config.sh -----------------------------------------------------------------------
MSG[render.need_envsubst]="envsubst is missing (gettext-base package)"
MSG[render.no_env]="%s does not exist. Copy .env.example to .env and fill it in."
MSG[render.no_tpl]="%s does not exist"
MSG[render.bad_workshop_id]="%s:%s: invalid workshop id '%s'"
MSG[render.missing_modid]="%s:%s: the mod_id for workshop %s is missing"
MSG[render.no_mods]="render-config: config/mods.txt does not exist: vanilla game (no mods).
render-config:   to add mods:  cp config/mods.example.txt config/mods.txt  (see docs/mods.md)"
MSG[render.vanilla_block]="render-config: ERROR: the server had mods and would now have none.
render-config:   current Mods=: %s
render-config:   If config/mods.txt is missing, restore it (on the VM 'make sync' brings it from your PC).
render-config:   To go vanilla on purpose:  ALLOW_VANILLA=1 make restart"
MSG[render.no_tpl_vars]="the template has no variables at all, check %s"
MSG[render.missing_vars]="variables missing from %s: %s"
MSG[render.empty_vars]="empty variables in %s: %s"
MSG[render.placeholders]="unresolved placeholders were left in the rendered ini"
MSG[render.no_sandbox]="render-config: config/servertest_SandboxVars.lua does not exist: vanilla rules (config/servertest_SandboxVars.example.lua).
render-config:   to customise them:  cp config/servertest_SandboxVars.example.lua config/servertest_SandboxVars.lua"
MSG[render.lua_copied]="render-config: lua files copied to %s/"

# --- scripts/wipe.sh --------------------------------------------------------------------------------
MSG[wipe.unknown_option]="unknown option: %s"
MSG[wipe.warning]="
  GAME WIPE.

  Deleted:    %s
              %s/db
              %s/backups (the server's own backups)

  Kept:       one final backup labelled 'pre-wipe' in backups/ and in the bucket, and all the
              versioned configuration in config/.

  Every player's character disappears. This cannot be undone except with scripts/restore.sh
  on the 'pre-wipe' backup."
MSG[wipe.prompt]="Type 'wipe' to continue: "
MSG[wipe.cancelled]="cancelled"
MSG[wipe.backup]="final backup labelled 'pre-wipe'"
MSG[wipe.backup_failed]="the pre-wipe backup failed; nothing is deleted"
MSG[wipe.no_data]="%s does not exist: nothing to back up"
MSG[wipe.deleting]="deleting %s"
MSG[wipe.done]="
wipe: done. Before starting the definitive game:

  1. Edit config/servertest_SandboxVars.lua (several options are fixed when the world is created).
  2. Edit config/mods.txt (the definitive mods; without the file the game is vanilla).
  3. Review config/servertest.ini.tpl (PVP, MaxPlayers, backups).
  4. From your PC: make sync (mods.txt is not in git; it only reaches the VM over rsync).
  5. make up"

# --- scripts/backup.sh ------------------------------------------------------------------------------
MSG[backup.unknown_option]="unknown option: %s"
MSG[backup.bad_label]="invalid label: '%s'"
MSG[backup.no_data]="%s does not exist: there is nothing to back up"
MSG[backup.saving]="the server is up: requesting a save before copying"
MSG[backup.save_failed]="WARNING: the RCON save failed; copying anyway (it may be inconsistent)"
MSG[backup.not_running]="the server is not running: copying the on-disk state as it is"
MSG[backup.skip_missing]="note: %s does not exist yet, skipping it"
MSG[backup.no_targets]="none of Saves/Server/db are in %s"
MSG[backup.creating]="creating %s"
MSG[backup.done]="done: %s"
MSG[backup.uploading]="uploading to %s:%s"
MSG[backup.uploaded]="uploaded"
MSG[backup.upload_failed]="WARNING: rclone failed. The local backup is in %s"
MSG[backup.local_only]="no BACKUP_BUCKET in .env or no rclone installed: local backup only"
MSG[backup.pruning]="deleting local backups older than %s days"

# --- scripts/restore.sh -----------------------------------------------------------------------------
MSG[restore.unknown_option]="unknown option: %s"
MSG[restore.usage]="usage: %s [--yes] <file|remote:bucket/name>"
MSG[restore.need_rclone]="rclone is required to download '%s'"
MSG[restore.downloading]="downloading %s"
MSG[restore.rclone_failed]="rclone did not leave %s"
MSG[restore.not_found]="'%s' does not exist and does not look like an rclone remote (missing 'remote:')"
MSG[restore.bad_tar]="%s is not a valid tar, or the decompressor is missing"
MSG[restore.warning]="
  About to RESTORE:  %s
  Over:              %s

  This stops the server, deletes the current world (Saves/Multiplayer/servertest and db/) and
  replaces it with the one in the backup. A safety backup labelled 'pre-restore' is taken first."
MSG[restore.prompt]="Type 'restore' to continue: "
MSG[restore.cancelled]="cancelled"
MSG[restore.safety_backup]="safety backup of the current state"
MSG[restore.safety_failed]="WARNING: the safety backup failed"
MSG[restore.removing]="deleting the current %s"
MSG[restore.extracting]="extracting"
MSG[restore.starting]="starting the server"
MSG[restore.done]="done. Follow the start-up with 'make logs'."

# --- scripts/update.sh ------------------------------------------------------------------------------
MSG[update.backup]="backup before touching anything"
MSG[update.backup_failed]="WARNING: the backup failed"
MSG[update.stopping]="clean shutdown"
MSG[update.pulling]="docker compose pull"
MSG[update.starting]="starting with the new image"
MSG[update.done]="done. Check the game version with: make logs | grep -i version"

# --- scripts/stop.sh --------------------------------------------------------------------------------
MSG[stop.not_running]="the container is not running, nothing to do"
MSG[stop.disable_restart]="disabling the container auto-restart"
MSG[stop.no_players]="no players connected, skipping the warning"
MSG[stop.warning]="warning the players (%ss)"
MSG[stop.save]="save"
MSG[stop.save_failed]="WARNING: the RCON save failed"
MSG[stop.quit]="quit"
MSG[stop.rcon_down]="WARNING: RCON does not answer; falling back to the entrypoint SIGTERM (which also sends quit)"
MSG[stop.waiting]="waiting for the container to finish saving (max %ss)"
MSG[stop.exited]="the container exited after %ss"
MSG[stop.ok]="ok"
MSG[stop.still_alive]="WARNING: still alive after %ss, forcing 'docker compose stop'"
MSG[stop.forced]="ok (forced shutdown)"

# --- scripts/restart.sh -----------------------------------------------------------------------------
MSG[restart.done]="restart: server starting. Follow it with 'make logs'."

# --- scripts/rcon.sh --------------------------------------------------------------------------------
MSG[rcon.no_env]="%s does not exist"
MSG[rcon.no_password]="RCONPASSWORD is missing from .env"
MSG[rcon.no_mcrcon]="mcrcon not found. Run 'make mcrcon' to build it in ./bin/mcrcon."
MSG[rcon.usage]="usage: %s <rcon command> [command...]"

# --- scripts/build-mcrcon.sh ------------------------------------------------------------------------
MSG[mcrcon.already_path]="build-mcrcon: there is already an mcrcon in the PATH (%s), no need to build"
MSG[mcrcon.already_local]="build-mcrcon: %s already exists"
MSG[mcrcon.need_gcc]="build-mcrcon: gcc is missing (apt install build-essential)"
MSG[mcrcon.need_git]="build-mcrcon: git is missing"
MSG[mcrcon.done]="build-mcrcon: %s ready"

# --- scripts/cloud-start.sh -------------------------------------------------------------------------
MSG[cloudstart.starting]="cloud-start: START on %s"
MSG[cloudstart.up_hint]="cloud-start: VM started. The server takes about a minute more to come up."
MSG[cloudstart.connect]="cloud-start: your friends connect to %s:16261"
MSG[cloudstart.up]="cloud-start: VM started."

# --- scripts/cloud-stop.sh --------------------------------------------------------------------------
MSG[cloudstop.unknown_option]="cloud-stop: unknown option: %s"
MSG[cloudstop.clean]="cloud-stop: clean server shutdown on %s"
MSG[cloudstop.ssh_failed]="cloud-stop: WARNING: the shutdown over SSH failed; the SOFTSTOP still triggers the systemd ExecStop"
MSG[cloudstop.no_ip]="cloud-stop: WARNING: could not resolve the IP; going straight to SOFTSTOP"
MSG[cloudstop.softstop]="cloud-stop: SOFTSTOP on %s"
MSG[cloudstop.done]="cloud-stop: VM stopped. OCI does not charge compute while the instance is STOPPED."

# --- scripts/idle-shutdown.sh -----------------------------------------------------------------------
MSG[idle.not_running]="the server is not running, nothing to do"
MSG[idle.rcon_down]="RCON does not answer; resetting the counter to be safe"
MSG[idle.players]="there are players connected (%s), resetting the counter"
MSG[idle.idle_for]="no players for %ss (threshold %ss)"
MSG[idle.dryrun]="DRY_RUN: this is where the server and the VM would be shut down"
MSG[idle.stopping]="stopping the server"
MSG[idle.backup]="backup"
MSG[idle.backup_failed]="WARNING: the backup failed"
MSG[idle.vm_off]="shutting down the VM"

# --- scripts/render-cloud-init.sh -------------------------------------------------------------------
MSG[cloudinit.unknown_mode]="unknown mode '%s': use 'https', 'ssh' or 'bot'"
MSG[cloudinit.no_out]="the output file is missing. Usage: %s {https|ssh|bot} output.yaml"
MSG[cloudinit.no_tofu]="'tofu' is not in the PATH"
MSG[cloudinit.done]="render-cloud-init: mode '%s' -> %s"

# --- scripts/encuesta.sh ----------------------------------------------------------------------------
MSG[survey.usage]="usage: scripts/encuesta.sh <command>

  up          syncs tools/ and infra/systemd/, installs the unit and starts the survey
  down        stops and disables the survey (the votes stay on the VM)
  estado      state of the unit and how many people voted
  resultados  downloads votos.jsonl and shows the tally (does not touch config/)
  aplicar     the tally plus the changes written into config/, with the diff"
MSG[survey.no_ip]="no VM IP. Try: scripts/encuesta.sh %s with VM_IP=203.0.113.10"
MSG[survey.step.sync]="Syncing the repository to the VM (%s)"
MSG[survey.step.install]="Installing and starting the survey"
MSG[survey.up]="Survey up at http://%s:%s"
MSG[survey.up_hint1]="Give that link to your friends. It closes when you run: make encuesta-down"
MSG[survey.up_hint2]="If it does not open from outside, the port is missing in the NSG:"
MSG[survey.up_hint3]="  survey_port = %s in infra/terraform/envs/prod/terraform.tfvars + make infra-apply"
MSG[survey.step.down]="Stopping the survey"
MSG[survey.down_ok]="Survey stopped. The votes are still in %s/votos.jsonl"
MSG[survey.down_hint]="To tally them: make encuesta-resultados"
MSG[survey.step.status]="Survey state on %s"
MSG[survey.status.nores]="the survey does not answer on port %s"
MSG[survey.status.votes]="lines in votos.jsonl:"
MSG[survey.status.novotes]="there is no votos.jsonl yet"
MSG[survey.step.results]="Downloading the votes"
MSG[survey.results_fail]="could not download %s/votos.jsonl (has anybody voted yet?)"
MSG[survey.results_ok]="Votes in %s"
MSG[survey.no_votes]="there is no %s. Run this first: make encuesta-resultados"
MSG[survey.unknown_cmd]="unknown command: %s"

# --- scripts/panel.sh -------------------------------------------------------------------------------
MSG[panel.usage]="usage: scripts/panel.sh <command>

  up                      syncs the repository, installs the unit, opens the port and starts the panel
  down                    stops the panel and closes the port in ufw (the tokens stay on the VM)
  estado                  state of the unit, /salud and the moderators loaded
  token add <name>        creates a token and prints the full URL for that moderator
  token list              lists the moderators (does not print the whole tokens)
  token revoke <name>     disables a moderator's token
  log [N]                 the last N recorded actions (default 20)"
MSG[panel.no_ip]="no VM IP. Try: scripts/panel.sh %s with VM_IP=203.0.113.10"
MSG[panel.step.sync]="Syncing the repository to the VM (%s)"
MSG[panel.step.install]="Installing and starting the panel"
MSG[panel.up]="Panel up at http://%s:%s"
MSG[panel.up_hint1]="Nothing is visible without a token: each moderator needs their own."
MSG[panel.up_hint2]="  make panel-token NAME=Fulano   -> prints the URL to send them privately"
MSG[panel.up_hint3]="If it does not open from outside, the port is missing in the NSG:"
MSG[panel.up_hint4]="  panel_port = %s in infra/terraform/envs/prod/terraform.tfvars + make infra-apply"
MSG[panel.step.down]="Stopping the panel"
MSG[panel.down_ok]="Panel stopped. The tokens are still in %s/moderadores.json"
MSG[panel.down_hint]="The port stays open in the NSG until you set panel_port = 0 and apply."
MSG[panel.step.status]="Panel state on %s"
MSG[panel.status.nores]="the panel does not answer on port %s"
MSG[panel.token.usage_add]="usage: scripts/panel.sh token add <name>"
MSG[panel.token.create_fail]="could not create the token"
MSG[panel.token.empty]="the token came out empty"
MSG[panel.token.created]="Token created for %s"
MSG[panel.token.hint1]="Send it by private message. That link IS the credential: whoever has it can"
MSG[panel.token.hint2]="restart the server. To revoke it: make panel-revoke NAME=%s"
MSG[panel.token.usage_revoke]="usage: scripts/panel.sh token revoke <name>"
MSG[panel.token.revoked]="Token revoked. The panel picks it up on its own, without restarting the service."
MSG[panel.token.usage]="usage: scripts/panel.sh token add|list|revoke"
MSG[panel.log.title]="Last %s panel actions"
MSG[panel.log.none]="(no actions recorded yet)"
MSG[panel.unknown_cmd]="unknown command: %s"

# --- scripts/watchdog.sh ----------------------------------------------------------------------------
MSG[watchdog.unit_not_installed]="the unit %s is not installed: skipping the check"
MSG[watchdog.rcon_grace]="the container started %ss ago (grace %ss): not checking RCON"
MSG[watchdog.rcon_fail]="RCON does not answer (%s/%s)"
MSG[watchdog.df_fail]="could not read df for %s"
MSG[watchdog.dryrun.restart]="DRY_RUN: this is where WARN_SECONDS=0 scripts/restart.sh would run"
MSG[watchdog.dryrun.critical]="DRY_RUN: this is where the server would be stopped, the bundle built and it would be started again"
MSG[watchdog.dryrun.disk]="DRY_RUN: this is where old local backups, logs older than 7 days and Docker layers would be deleted"
MSG[watchdog.dryrun.autorepair]="DRY_RUN: this is where scripts/autorepair.sh would run"
MSG[watchdog.stopping]="stopping the server"
MSG[watchdog.stop_failed]="WARNING: stop.sh failed, falling back to 'docker compose down'"
MSG[watchdog.diagnostic]="diagnostics in %s"
MSG[watchdog.starting]="starting"
MSG[watchdog.started]="the server started after %ss"
MSG[watchdog.disk_freed]="free space: %s MB -> %s MB"
MSG[watchdog.escalated]="[ESCALATED] %s (repeated, not notified again): %s"
MSG[watchdog.autorepair_off]="CLAUDE_AUTOREPAIR is not 1: not calling autorepair.sh"
MSG[watchdog.autorepair_missing]="WARNING: CLAUDE_AUTOREPAIR=1 but scripts/autorepair.sh does not exist"
MSG[watchdog.autorepair_call]="calling scripts/autorepair.sh (attempt %s today for '%s')"
MSG[watchdog.autorepair_rc]="autorepair.sh exited with code %s (see %s)"
MSG[watchdog.lock_unwritable]="WARNING: cannot write the lock %s: skipping this pass"
MSG[watchdog.lock_busy]="an operation is already in progress (watchdog or mod-updater), skipping this one"
MSG[watchdog.healthy]="healthy: unit active, container up, RCON answering, log clean"

# --- scripts/mod-updater.sh -------------------------------------------------------------------------
MSG[modupd.dryrun.notify]="DRY_RUN: this is where it would notify [%s] %s -- %s"
MSG[modupd.dryrun.servermsg]="DRY_RUN: this is where it would send over RCON servermsg \"%s\""
MSG[modupd.servermsg_fail]="WARNING: could not send the servermsg"
MSG[modupd.dryrun.restart]="DRY_RUN: this is where WARN_SECONDS=%s scripts/restart.sh would run (mods: %s)"
MSG[modupd.restarting]="restarting the server (WARN_SECONDS=%s) because of: %s"
MSG[modupd.no_mods]="config/mods.txt declares no mods: nothing to check"
MSG[modupd.api_fail]="the Steam API did not answer (curl failed): doing nothing on this pass"
MSG[modupd.compare_fail]="the API response is unusable (comparar.py exited with %s): doing nothing"
MSG[modupd.check.no_mods]="mod-updater: config/mods.txt declares no mods"
MSG[modupd.check.api_fail]="mod-updater: the Steam API did not answer"
MSG[modupd.lock_unwritable]="WARNING: cannot write the lock %s: skipping this pass"
MSG[modupd.lock_busy]="another operation is in progress (watchdog or mod-updater), skipping this pass"
MSG[modupd.ops_busy]="a restart/stop/wipe/update/backup is running, skipping this pass"
MSG[modupd.weird]="mods without a usable comparison: %s"
MSG[modupd.inconsistent]="inconsistent state (waiting phase with no pending mods): closing the cycle"
MSG[modupd.waiting_steamcmd]="waiting for SteamCMD to finish downloading: %s"
MSG[modupd.closed_cycle]="the pending mods came up to date without us restarting: closing the cycle"
MSG[modupd.all_current]="every declared mod is up to date"
MSG[modupd.only_log]="%s is still out of date and MOD_UPDATE_AUTO_RESTART=0: only recording it"
MSG[modupd.rcon_down]="RCON does not answer: postponing the mod restart (the watchdog handles that)"
MSG[modupd.pending]="restart pending in %s minute(s) because of: %s"

# --- scripts/autorepair.sh --------------------------------------------------------------------------
MSG[autorepair.usage]="usage: scripts/autorepair.sh --bundle <dir> --motivo <text> [--intentos <n>]

  --bundle    the diagnostics directory the watchdog built (required)
  --motivo    what the watchdog detected: crash-loop, patron-fatal, oom, rcon, disco
  --intentos  how many times it escalated today for the same reason (default 1)"
MSG[autorepair.unknown_option]="autorepair: unknown option: %s"
MSG[autorepair.disabled]="CLAUDE_AUTOREPAIR is not 1 in .env: not calling Claude"
MSG[autorepair.bad_bundle]="autorepair: ERROR: --bundle has to point to an existing directory"
MSG[autorepair.no_quota]="no quota left (%s/%s in the last hour, %s/%s today)"
MSG[autorepair.missing_file]="autorepair: %s is missing"
MSG[autorepair.dryrun]="DRY_RUN: the command that would run (the prompt is truncated)"
MSG[autorepair.running]="running claude (timeout %s, max-turns %s)"
MSG[autorepair.exit]="claude exited with %s (is_error=%s, turns=%s, cost USD %s)"
MSG[autorepair.no_text]="(no text: check autorepair.json and autorepair.err)"

# --- Makefile ---------------------------------------------------------------------------------------
MSG[make.dirs.done]="dirs: data/zomboid and data/workshop ready (%s:%s)"
MSG[make.up.started]="up: starting. Follow the progress with 'make logs'; the server is up when '*** SERVER STARTED ****' shows up."
MSG[make.rcon.usage]="usage: make rcon CMD=players"
MSG[make.remote_rcon.usage]="usage: make remote-rcon CMD=players"
MSG[make.status.players]="--- players ---"
MSG[make.status.rcon_down]="(RCON does not answer: the server is not up yet)"
MSG[make.restore.usage]="usage: make restore FILE=backups/zomboid-YYYYmmdd-HHMM.tar.zst"
MSG[make.require_ip]="No VM_IP. Options:
  make remote-status VM_IP=203.0.113.10
  cd %s && tofu output -raw public_ip     (needs the local .tfstate)"
MSG[make.require_bot_ip]="No BOT_IP. Options:
  make bot-status BOT_IP=203.0.113.10
  cd %s && tofu output -raw bot_public_ip   (needs bot_enabled = true)"
MSG[make.remote_diff.note]="If there are changes, bring them into the repository by hand and commit them; the VM is re-cloned on every tofu apply."
MSG[make.watchdog.installed]="watchdog: installed. First check in under 2 minutes; see it with 'make watchdog-status'."
MSG[make.watchdog.discord]="watchdog: for Discord alerts, set DISCORD_WEBHOOK_URL in the .env ON THE VM (see docs/self-healing.md)."
MSG[make.modupd.installed]="mod-updater: installed. First check in under 5 minutes; see it with 'make mod-updater-status'."
MSG[make.modupd.policy]="mod-updater: the restart policy comes from the .env ON THE VM (MOD_UPDATE_*, see docs/mods.md)."
MSG[make.notifier.installed]="notifier: installed. With the server up it publishes the current state in under a minute."
MSG[make.notifier.webhook]="notifier: needs DISCORD_WEBHOOK_URL in the .env ON THE VM (see docs/discord.md)."
MSG[make.sync.done]="sync: configuration and scripts updated on %s"
MSG[make.sync.note]="sync: .env, data/ and bin/ are NOT synced (they belong to the VM)."
MSG[make.sync.hint]="sync: to apply the changes: make remote-restart (or make sync RESTART=1)"
MSG[make.no_log]="(no log yet)"
MSG[make.bot.installed]="bot: installed. The /pz commands show up in Discord as soon as it connects ('make bot-status')."
MSG[make.panel_token.usage]="usage: make panel-token NAME=Fulano"
MSG[make.panel_revoke.usage]="usage: make panel-revoke NAME=Fulano"
MSG[make.idle.installed]="idle-shutdown: enabled. With 0 players for IDLE_MINUTES the VM shuts itself down."
MSG[make.idle.note]="idle-shutdown: only makes sense with the bot running, otherwise nobody can start it again."
MSG[make.idle.no_line]="(no idle-shutdown line)"
